sterling/sterling/urls.py
from django.contrib.auth.views import login, logout
from django.conf.urls import patterns, include, url
from splash.views import SplashFormView
from vanilla import RedirectView
from apps.views import AppListView, AppCreateView, AppDetailView, SterlingRegistrationView, \
AppDemographicsView, AppAlgorithmsView, AppSettingsView, AppHomeView, AppHelpView


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# TODO: Separate urls into different apps
urlpatterns = patterns('',
    # Examples:
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', SplashFormView.as_view(), name="index"),
    url(r'^login/$', login, {'template_name': 'login.html'}, name="login"),
    url(r'^logout/$', logout, {'next_page': '/'}, name="logout"),
    url(r'^apps/$', AppHomeView.as_view(), name="dashboard"),
    url(r'^apps/list/$', AppListView.as_view(), name='app_list'),
    url(r'^apps/detail/(?P<pk>\d+)/$', AppDetailView.as_view(), name="detail_app"),
    url(r'^apps/detail/(?P<pk>\d+)/demographics/$', AppDemographicsView.as_view(), name="demographics_app"),
    # url(r'^apps/detail/(?P<pk>\d+)/algorithms/$', AppAlgorithmsView.as_view(), name="algorithms_app"),
    url(r'^apps/detail/(?P<pk>\d+)/settings/$', AppSettingsView.as_view(), name="settings_app"),
    url(r'^help/$', AppHelpView.as_view(), name="help"),
    url(r'^apps/create/$', AppCreateView.as_view(), name="create_app"),
    url(r'^accounts/register/', SterlingRegistrationView.as_view(), name="registration_register"),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^', include('suggestions.urls')),
    url(r'^django-rq/', include('django_rq.urls')),
)

sterling/apps/models.py
from annoying.fields import AutoOneToOneField
import datetime

from django.conf import settings
from django.db import models

from suggestions.models import AppUser, AppUserMembership, Suggestion, Algorithm

class MobileApp(models.Model):
    ''' Represents an app that is signed up for the platform '''
    facebook_id = models.CharField(max_length=50, primary_key=True)
    name = models.CharField(max_length=200)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, through='DevMembership') # App admins
    invitation_message = models.TextField(blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    link = models.URLField(max_length=1000, blank=True, null=True) # Link to app in App Store

    # TODO: Point to actual default algorithm
    default_algorithm = models.ForeignKey(Algorithm, blank=True, null=True)

    def __unicode__(self):
        return self.name

    # def algorithms_used(self):
    #     return Algorithm.objects.filter()

    def num_users(self, datetime=datetime.datetime.now()):
        ''' Returns number of users signed up for the app
        Optional datetime parameter that gets number of users before that datetime.
        '''
        return AppUserMembership.objects.filter(mobile_app=self, created__lt=datetime).count()

    # TODO: Investigate these queries to see if they're fast (they're probably not)
    # def num_suggested(self, datetime=datetime.datetime.now()):
    #     ''' Returns number of invitations that were clicked, with optional datetime parameter '''
    #     return Suggestion.objects.filter(suggestion_list__app_user_membership__mobile_app=self,
    #                                     created__lt=datetime).count()

    def num_invited(self, datetime=datetime.datetime.now()):
        ''' Returns number of people invited to the app
        Optional datetime parameter that gets number of users invited before that datetime. 
        '''
        return Suggestion.objects.filter(suggestion_list__app_user_membership__mobile_app=self,
                                         times_invited__gt=0,
                                         created__lt=datetime).count()

    def num_invitations_joined(self, datetime=datetime.datetime.now()):
        ''' Returns number of invitations that resulted in app signups '''
        return Suggestion.objects.filter(suggestion_list__app_user_membership__mobile_app=self,
                                            accepted=True,
                                            created__lt=datetime).count()

    def save(self, *args, **kwargs):
        super(MobileApp, self).save(*args, **kwargs)
        try:
            settings = self.appsettings
        except AppSettings.DoesNotExist:
            AppSettings.objects.create(mobile_app=self)
        

class AppSettings(models.Model):
    ''' Contains settings chosen for a given app's algorithms
    and maybe eventually for other stuff'''
    mobile_app = AutoOneToOneField(MobileApp)

    likes_sports = models.BooleanField(default=False)
    likes_technology = models.BooleanField(default=False)
    likes_books = models.BooleanField(default=False)
    likes_nature = models.BooleanField(default=False)
    likes_games = models.BooleanField(default=False)
    likes_restaurants = models.BooleanField(default=False)
    likes_music = models.BooleanField(default=False)

    POLITICAL_CHOICES = (
        (0, 'No bias'),
        (-1, 'Conservative'),
        (1, 'Liberal')
    )

    political_bias = models.IntegerField(POLITICAL_CHOICES, blank=True, null=True)
    same_city = models.BooleanField(default=False)
    city = models.CharField(max_length=250, null=True, blank=True)

    SOCIAL_CIRCLE_CHOICES = (
        ("fa", "Family"), 
        ("co", "Colleagues"), 
        ("colf", "College Friends"),
        ("hsf", "High School Friends") 
    )

    social_circle = models.CharField(choices=SOCIAL_CIRCLE_CHOICES, max_length=100, blank=True, null=True)

    def dict_rep(self):
        data = {}


class DevMembership(models.Model):
    ''' 'Through' model for app signups. '''
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    mobile_app = models.ForeignKey(MobileApp)
    date_joined = models.DateField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)







    

sterling/splash/models.py
from django.db import models

# Create your models here.
class SignUp(models.Model):
    ''' Represents an interested user! '''
    email = models.EmailField()

    def __unicode__(self):
        return self.email

sterling/splash/views.py
# Create your views here.
from validate_email import validate_email

from apps.models import MobileApp

from django.views.generic import View
from django.shortcuts import render, redirect
from django.http import HttpResponse

from .models import SignUp

class SplashFormView(View):
    template_name = "splash.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        email = request.POST.get('email', '')
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        
        if validate_email(email):
            signup = SignUp(email=email)
            signup.save()
            return render(request, self.template_name, {"signup_success": True})
        else:
            return render(request, self.template_name, {"error": True})

    def get_queryset(self):
        try:
            return MobileApp.objects.filter(users__exact=self.request.user)
        except TypeError:
            return None


    def dispatch(self, request, *args, **kwargs):
        if self.get_queryset():
            return redirect('apps/detail/%d' % int(self.get_queryset()[0].pk) )
        #return self.as_view()
        return render(request, self.template_name)

sterling/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="shortcut icon" href="../../assets/ico/favicon.png">

  <title>{% block title %}Sterling{% endblock title %}</title>

  <nav class="navbar navbar-default" role="navigation">
    <div class='navbar-header'>
      <a class="navbar-brand" href="/"><i class="fa fa-circle-o" style="padding-right: 3px"></i>   sterling </a>
    </div>
    <div class="collapse navbar-collapse navbar-ex1-collapse">


      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'help' %}">Help</a></li>
        {% if user.is_authenticated %}

        {% for app in user.mobileapp_set.all %}
            <li><a href="{% url 'detail_app' app.pk %}"> {{ app }} </a></li>
        {% endfor %}

        <li><a href="{% url "app_list" %}">My Apps</a></li>

        <li><a href="{% url "logout" %}">Logout</a></li>

        {% else %}
        <li><a href="{% url "index" %}">Home</a></li>
  <!--       <li><a href="{% url "login" %}">Login</a></li> -->
  <!--       <li><a href="{% url "registration_register" %}">Sign up</a></li>
   -->      {% endif %}
      </ul>
    </div>
  </nav>

  <!-- Bootstrap core CSS -->
  <link href="//netdna.bootstrapcdn.com/bootswatch/3.0.0/cerulean/bootstrap.min.css" rel="stylesheet">
  <link href="{% static "css/my.css" %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href='http://fonts.googleapis.com/css?family=Lato:400,700,900' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Merriweather' rel='stylesheet' type='text/css'>

  <!-- Font Awesome -->
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.1/css/font-awesome.css" rel="stylesheet">
  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
      <![endif]-->
    </head>

    <body>

      {% block content %}

      {% endblock content %}


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>    
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="http://malsup.github.com/jquery.cycle2.js"></script>

    
    
  </body>
  </html>

sterling/templates/dashboard.html
{% extends "base.html" %}

{% block content %}

<div class="dashboard">
    <h2> My Apps </h2>
    <ul>
        {% for app in object_list %}
            <li><a href="{% url 'detail_app' app.pk %}"> {{ app.name }} </a></li>
        {% endfor %}
    </ul>

    <a href="{% url 'create_app' %}" class="btn btn-primary">Add an app</a>

</div>

{% endblock content %}

sterling/templates/help.html
{% extends "base.html" %}

{% block content %}


<div class="documentation">
        <h2 id="apidocumentation">API Documentation</h2>

        <p>To start using the API, you need to have a Facebook app. The API only works on users that have signed up for your Facebook app.
        Refer to the Facebook documentation to get started with the Facebook API.</p>

        <p>Once you have a Facebook App with some users, register for an account on our website. You will need your app's Facebook ID 
        to register.</p>

        <p>After you have registered, make the following calls to access the API:</p>

        <p>1) <strong>POST</strong>: <code>www.sterlingshare.com/api/register/</code>
        This registers your request, and starts running the algorithms for the particular user. It takes the following parameters:</p>
        <ul>
        <li><code>app_facebook_id</code>: Your app's Facebook ID</li>
        <li><code>facebook_id</code>: The user's Facebook ID</li>
        <li><code>oauth_token</code>: The OAuth Token for the particular user</li>
        </ul>

        <p>It returns an 201 upon success.</p>

        <p>2) <strong>GET</strong>: <code>www.sterlingshare.com/api/friends/</code>
        This fetches the suggestion list for the given user. It takes the following parameters:
        </p>
        <ul>
        <li><code>app_facebook_id</code>: Your app's Facebook ID</li>
        <li><code>facebook_id</code>: The user's Facebook ID</li>
        </ul>

        <p>On success, it returns:</p>
        <ul>
        <li><code>friends</code>: An ordered list of the user's best friends.</li>
        <li><code>list_id</code>: A unique ID for the list. Save this if you wish to send invites to the users.</li>
        </ul>

        <p>3) <strong>POST</strong>: <code>www.sterlingshare.com/api/friends/</code>
        This sends a Facebook message to the selected friends. It also collects statistics that you can see on the website.
        It takes the following parameters:</p>
        <ul>
        <li><code>list_id</code>: The ID of the suggestion list returned by the GET request.</li>
        <li><code>friends_seen</code>: A list of the friends that the user saw (i.e. were on the front page). If you don't know, feel free to include 
        all of the users friends. </li>
        <li><code>friends_invited</code>: A list of the friends that the user selected to invite. WARNING: A private facebook message will be sent to each of these users.</li>
</ul>

        <p>It returns a 200 on success.</p>
</div>

{% endblock content %}

sterling/templates/login.html
{% extends "base.html" %}

{% block content %}
{% if form.errors %}
<p> You have the wrong username or password. Please try again. </p>
{% endif %}
<div class="col-md-2">
<div class="container">
<div class="login">
<form role="form" method="post" action="{% url "login" %}">
  {% csrf_token %}
  <div class="input-group">
    <p> Username: {{form.username}}</p>
    <p> Password: {{form.password}}</p>

        <input type="submit" class="btn btn-primary btn-large btn-block" value="Login" />
        <input type="hidden" name="next" value="{{ next }}"/>
    </div>
</form>

</div>
</div>
</div>

{% endblock content %}

sterling/templates/logout.html
{% extends "base.html" %}

{% block content %}
<p> You are now logged out. </p>
{% endblock content %}

sterling/templates/signup.html
{% extends "base.html" %}

{% block content %}

<form method="post" action="{% url 'signup' %}">
{% csrf_token %}
{{ form.as_p }}

<input type="submit" value="Sign up!" />

</form>


{% endblock content %}

sterling/templates/splash-screenshots.html
{% extends "splash.html" %}

{% block splash-screenshots %}


{% endblock splash-screenshots %}

sterling/templates/splash.html
{% extends "base.html" %}

{% block content %}
  <div class="container">
<!--         <div class="absolute-center">
-->          <div class="row">
        {% if signup_success %}
        <div class="alert alert-dismissable alert-success">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            Thank you for your interest!
        </div>
        {% elif error %}
        <div class="alert alert-dismissable alert-danger">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            Invalid email. Please try again.
        </div>
        {% endif %}

        <div class="col-md-6 col-md-push-6">
          <div class="logo-container">
            <h1 class="logo">Sterling</h1>
            <h3 class="tagline"> User acquisition made easy </h3>
            <hr>
          
          <form class="email-form" role="form" method="post" action="{% url 'index' %}">
            {% csrf_token %}
            <div class="input-group email-input">
              <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
              <input type="email" class="form-control" name="email" placeholder="Enter your email to get on the waiting list.">
            </div>
            <button type="submit" class="btn btn-primary btn-large btn-block btn-submit">Submit</button>
          </form>
          <p class="sign-in"> or <a href="{% url "login" %}">Sign in</a></p>
        </div>
        </div>
        <div class="col-md-6 col-md-pull-6">
          <div class="slideshow-container">
            <div class="cycle-slideshow" data-cycle-fx='none' data-cycle-timeout="10">
               <img class="img-responsive iphone-screenshot center-block screenshot-1" src="static/img/screenshots/screenshot-1.png"/>
               <img class="img-responsive iphone-screenshot center-block screenshot-2" src="static/img/screenshots/screenshot-2.png"/>
               <img class="img-responsive iphone-screenshot center-block screenshot-2" src="static/img/screenshots/screenshot-3.png"/>
               <img class="img-responsive iphone-screenshot center-block screenshot-2" src="static/img/screenshots/screenshot-4.png"/>
               <img class="img-responsive iphone-screenshot center-block screenshot-2" src="static/img/screenshots/screenshot-5.png"/>
               <img class="img-responsive iphone-screenshot center-block screenshot-1" src="static/img/screenshots/screenshot-6.png"/>
               <img class="img-responsive iphone-screenshot center-block screenshot-2" src="static/img/screenshots/screenshot-7.png"/>
               <img class="img-responsive iphone-screenshot center-block screenshot-2" src="static/img/screenshots/screenshot-8.png"/>
               <img class="img-responsive iphone-screenshot center-block screenshot-2" src="static/img/screenshots/screenshot-9.png"/>
               <img class="img-responsive iphone-screenshot center-block screenshot-2" src="static/img/screenshots/screenshot-10.png"/>
            </div>
         </div>
        </div>
      </div>
  </div> <!-- /container -->
</div>
<hr>
<div class="second">
  <div class="container description-container">
    <div class="row description-row">
      <div class="col-md-6">
        <div class="description description-left">
        <h2> Sharing done right </h2>
        <p> Say goodbye to alphabetical friend lists. Sterling presents users with a friend list designed to spread your app.  </p>
        </div>
      </div>
      <div class="col-md-3 col-md-offset-2">
        <i class="fa fa-facebook-square bar-graph-icon" style="padding-left: 15px"></i> 
      </div>
    </div>
    <div class="row description-row">
      <div class="col-md-3">
        <i class="fa fa-bar-chart-o bar-graph-icon"></i> 
      </div>
      <div class="col-md-6 col-md-offset-3">
        <div class="description description-left">
          <h2> Social analytics </h2>
          <p> Visualize your app spreading across social networks. Know where your app is going so you can make the best decisions for your business.</p>
        </div>
      </div>
    </div>
    <div class="row description-row">
      <div class="col-md-6">
        <div class="description description-left">
          <h2> Easy to use </h2>
          <p> Drop this into your app in less than 15 minutes. Then sit back, have a beer, and see your app go viral. </p>
        </div>
      </div>
      <div class="col-md-3 col-md-offset-2">
        <i class="fa fa-group bar-graph-icon"></i> 
      </div>
    </div>
  </div>
  <hr>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="signup-form-again">
        <h3> We're in closed beta. Sign up below for updates. </h3>
        <form class="email-form" role="form" method="post" action="{% url 'index' %}">
              {% csrf_token %}
              <div class="input-group email-input">
                <span class="input-group-addon"><span class="glyphicon glyphicon-envelope"></span></span>
                <input type="email" class="form-control" name="email" placeholder="Enter your email">
              </div>
              <button type="submit" class="btn btn-primary btn-large btn-block btn-submit">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock content %}